### ISSUE TITLE
Feature: Use real ff_schedule instead of simulated schedule

### ISSUE THREAD

**Issue by tanho63** [ffverse/ffsimulator#5]
(can just use ff_schedule (?))

**Comment by tanho63** [comment]
Will not be included in v1.0 - most likely will aim to add for v1.1

**Comment by tonyelhabr** [comment]
did you want my help with this? or do you already have an idea of how to handle this?

**Comment by tanho63** [comment]
It should just require "run ff_schedule once then duplicate it n_seasons times", but I think the function to summarise weeks needs some minor rework possibly...

Also with using actual schedules, I wonder if it should only simulate unplayed games...

I have ideas but if you're keen to help I wouldn't say no!
