### ISSUE TITLE
ff_simulate doesn't work - error regarding actual_schedule

### ISSUE THREAD

**Issue by christianlohr9** [ffverse/ffsimulator#6]
Hi Tan,

unfortunately I'm not able to use this freaking awesome package. 
The following error (installed the stable version) occurs while running ff_simulate (regardless of what connection I build): 

**Reprex**
``` r
library(tidyverse)
#> Warning: package 'tibble' was built under R version 4.0.5
#> Warning: package 'tidyr' was built under R version 4.0.4
#> Warning: package 'dplyr' was built under R version 4.0.5
#> Warning: package 'forcats' was built under R version 4.0.5
library(ffscrapr)
library(ffsimulator)
#> Warning: package 'ffsimulator' was built under R version 4.0.5
# install.packages("ffsimulator", repos = "https://ffverse.r-universe.dev") # stable version
# remotes::install_github("ffverse/ffsimulator")

# conn <- ffscrapr::sleeper_connect(2021,"708433394454851584")

conn <- mfl_connect(2021,22627)

sims <- ff_simulate(conn, n_seasons = 100, n_weeks = 14, best_ball = FALSE)
#> Error in checkmate::assert_flag(actual_schedule): object 'actual_schedule' not found
```

<sup>Created on 2021-07-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I guess the missing league ID causes some problems...Seems like it didn't take it from the conn...?

```r
<MFL connection 2021_>
List of 5
 $ platform   : chr "MFL"
 $ season     : chr "2021"
 $ league_id  : chr(0) 
 $ APIKEY     : NULL
 $ auth_cookie: NULL
 - attr(*, "class")= chr "mfl_conn"
```
**Expected behavior**
I want ff_simulate() to run and simulate some fancy seasons ;)

**Session information**
Please copy the output of `sessionInfo()` into the box below.
```r
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_Germany.1252  LC_CTYPE=English_Germany.1252    LC_MONETARY=English_Germany.1252
[4] LC_NUMERIC=C                     LC_TIME=English_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ffsimulator_0.2.2.02 RSQLite_2.2.1       

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6        compiler_4.0.3    pillar_1.6.1      tools_4.0.3       digest_0.6.27     bit_4.0.4        
 [7] memoise_2.0.0     evaluate_0.14     lifecycle_1.0.0   tibble_3.1.2      checkmate_2.0.0   pkgconfig_2.0.3  
[13] rlang_0.4.11      reprex_0.3.0      DBI_1.1.0         xfun_0.19         fastmap_1.1.0     httr_1.4.2       
[19] knitr_1.30        fs_1.5.0          vctrs_0.3.8       bit64_4.0.5       glue_1.4.2        R6_2.5.0         
[25] processx_3.4.5    fansi_0.5.0       rmarkdown_2.6     ratelimitr_0.4.1  callr_3.5.1       clipr_0.7.1      
[31] blob_1.2.1        magrittr_2.0.1    ffscrapr_1.4.3.06 whisker_0.4       ps_1.5.0          backports_1.2.1  
[37] ellipsis_0.3.2    htmltools_0.5.1.1 assertthat_0.2.1  utf8_1.2.1        cachem_1.0.5      crayon_1.4.1  
```

**Additional question:**
My assumption is, that this package works for sleeper_connect as well, is that correct?

Best regards,
Christian

**Comment by tanho63** [comment]
Ack! It's not quite ready yet 😂 I'm still experimenting with various things I want to release. 

Just got rid of it temporarily, if you install now it should not have an actual schedule argument (0.2.2.03).

Yes, the intention is that you can pass in any ff_connect() and it should work - you may need the development version of ffscrapr (1.4.3.06+) to use sleeper because there's a bugfix for ff_league() there that I haven't brought to CRAN yet

**Comment by christytc10** [comment]
Came to report the same, will try that workaround for sleeper :) 
Package is absolutely amazing btw, thanks for it

**Comment by tanho63** [comment]
I swear I'm going to submit to CRAN on Saturday, folks, but my goodness I appreciate the willingness to try my bleeding edge stuff!

**Comment by christytc10** [comment]
FWIW, getting the latest ffsimulator worked fine for my Sleeper league (without needing to upgrade ffscrapr explicitly)

**Comment by tanho63** [comment]
Closing: actual_schedule feature punted to future versions (maybe even 1.1.0) and should no longer be causing issues as of this version. Happy to take bug reports on new issues
