### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jacobakaye** [ffverse/ffsimulator#69]
```r
── Starting simulation 2024-02-15 22:31:57.394194 ────────────────────────────────────────────────────────────────────────────────
✔ Importing data ... done
✔ Generating Projections ... done
Error: 'unnest.' is not an exported object from 'namespace:tidytable'
```

**Comment by tanho63** [comment]
Have you reinstalled from the development version?

**Comment by jacobakaye** [comment]
It worked but the output was just this: 
![image](https://github.com/ffverse/ffsimulator/assets/126515518/fc7de2a1-c058-4242-aa63-35d3871c31ec)

**Comment by tanho63** [comment]
Please open a new issue and fill out the issue template: https://github.com/ffverse/ffsimulator/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=
