### ISSUE TITLE
weekly sim issue

### ISSUE THREAD

**Issue by jacobakaye** [ffverse/ffsimulator#71]
> sim_week <- ff_simulate_week(conn = espn_conn, n = 10)
── Starting simulation 2024-09-11 15:00:30.143731 ───────────────────────────────────────────────────────────────────
✔ Importing data ... done
Error in `[.data.table`(fp_latest, , c("player_name", "fantasypros_id",  : 
  column(s) not found: [sportradar_id]

**Comment by tanho63** [comment]
Looks like FP scrape no longer has sportradar id :(
